trigger:
- main  # Or specify the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Choose the appropriate image based on your requirements

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    chmod +x LT
    ./LT --user shubhamr@lambdatest.com --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh
  displayName: 'Run LambdaTest Command'
