trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Run LT command in background'
  inputs:
    targetType: 'inline'
    script: |
      Start-Process -NoNewWindow -FilePath "LT" -ArgumentList "--user shubhamr@lambdatest.com --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh" -Wait

- task: PythonScript@0
  displayName: 'Run python script'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'path/to/your/python_script.py'
