trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Run LT command in background'
  inputs:
    targetType: 'inline'
    script: |
      Start-Process -NoNewWindow -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command ./LT --user shubhamr@lambdatest.com --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh" -PassThru
      Start-Sleep -Seconds 30

- task: PythonScript@0
  displayName: 'Run python script'
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'path/to/your/python_script.py'
