trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: RunLTCommand1
  displayName: 'Run LT Command 1'
  steps:
  - task: PowerShell@2
    displayName: 'Run LT Command 1'
    inputs:
      targetType: 'inline'
      script: |
        Start-Process -FilePath "./LT" -ArgumentList "--user shubhamr@lambdatest.com --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --tunnelName Ritam1"
        Start-Sleep -Seconds 300  # 5 minutes (300 seconds)

- job: RunLTCommand2
  displayName: 'Run LT Command 2'
  steps:
  - task: PowerShell@2
    displayName: 'Run LT Command 2'
    inputs:
      targetType: 'inline'
      script: |
        Start-Process -FilePath "./LT" -ArgumentList "--user shubhamr@lambdatest.com --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --tunnelName Ritam3"
        Start-Sleep -Seconds 300  # 5 minutes (300 seconds)
