trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Run LT command in background'
  inputs:
    targetType: 'inline'
    script: |
      # Store the current file path in a variable
      $currentFilePath = $PSScriptRoot

      # Start the LT command
      Start-Process -NoNewWindow -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command ./LT --user shubhamr@lambdatest.com --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh" -PassThru

      # Wait for 30 seconds
      Start-Sleep -Seconds 30

- task: PowerShell@2
  displayName: 'Echo current file path'
  inputs:
    targetType: 'inline'
    script: |
      ls 
      pip install Appium-Python-Client
      pip install selenium==3.12.0
      python android.py