name: Background Commands Pipeline

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  background_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Run LT command in background with delay
        run: |
          ./LT --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm > lt.log 2>&1 &
          sleep 60

      - name: Run mitmdump command in background
        run: |
          nohup mitmdump -s proxy.py > mitmdump.log 2>&1 & python proxy1.py

      - name: Run python browser3.py in background
        run: |
          python browser3.py > browser.log 2>&1 & python proxy2.py
