name: Execute Remote Commands on Machines

on: [push]

jobs:
  remote-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Execute commands on Machine 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MACHINE1 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pip install mitmproxy
            pip install selenium
            nohup ./LT --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm &
            nohup mitmdump -s proxy.py > mitmdump.log 2>&1 &
            python browser3.py
      
      - name: Execute commands on Machine 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MACHINE2 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pip install mitmproxy
            pip install selenium
            nohup ./LT --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm &
            nohup mitmdump -s proxy.py > mitmdump.log 2>&1 &
            python browser3.py
      
      - name: Execute commands on Machine 3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_MACHINE3 }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pip install mitmproxy
            pip install selenium
            nohup ./LT --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm &
            nohup mitmdump -s proxy.py > mitmdump.log 2>&1 &
            python browser3.py
