name: Parallel Execution with Specific Scripts

on:
  push:
    branches:
      - main  # Adjust this to match the branches you want to trigger the workflow

jobs:
  run-in-parallel:
    runs-on: ubuntu-latest  # Assuming you are using Ubuntu runners
    strategy:
      matrix:
        instance: [1, 2, 3]  # Define a matrix to run 3 instances
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        sudo apt-get update
        pip install selenium==4.12.0
        sudo apt-get install -y mitmproxy  # Install mitmproxy or any other dependencies

    - name: Download and Install LT Tunnel
      run: |
        curl -L https://downloads.lambdatest.com/tunnel/v3/linux/64bit/LT -o LT
        chmod +x LT

    - name: Execute Commands
      run: |
        nohup ./LT --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm --tunnelName Ritam${{ matrix.instance }} &
        sleep 5  # Allow some time for the LT command to initialize
        nohup mitmdump -s proxy.py > mitmdump${{ matrix.instance }}.log 2>&1 &
        python proxy${{ matrix.instance }}.py & cat proxy.py
