name: Run Commands on Linux Machines

on:
  push:
    branches:
      - main

jobs:
  machine1:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies and run command on Machine 1
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mitmproxy
          pip3 install selenium
          nohup ./LT.exe --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm &
          nohup mitmdump -s proxy.py > mitmdump.log 2>&1 &
          python3 proxy1.py

  machine2:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies and run command on Machine 2
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mitmproxy
          pip3 install selenium
          nohup ./LT.exe --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm &
          nohup mitmdump -s proxy.py > mitmdump.log 2>&1 &
          python3 proxy2.py

  machine3:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies and run command on Machine 3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install mitmproxy
          pip3 install selenium
          nohup ./LT.exe --user shubhamr --key dl8Y8as59i1YyGZZUeLF897aCFvIDmaKkUU1e6RgBmlgMLIIhh --proxy-port 8080 -v --shared-tunnel --proxy-host localhost --ingress-only --mitm &
          nohup mitmdump -s proxy.py > mitmdump.log 2>&1 &
          python3 proxy3.py
